<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-02-17T23:30:43 IST" name="Suite" finished-at="2025-02-17T23:30:46 IST" duration-ms="3226">
    <groups>
      <group name="smoke">
        <method signature="LoginTest.verifyWhetherUserIsAbleLoginSuccessfullywithValidUsernameandValidPassword()[pri:0, instance:testscript.LoginTest@12591ac8]" name="verifyWhetherUserIsAbleLoginSuccessfullywithValidUsernameandValidPassword" class="testscript.LoginTest"/>
      </group> <!-- smoke -->
    </groups>
    <test started-at="2025-02-17T23:30:43 IST" name="Test" finished-at="2025-02-17T23:30:46 IST" duration-ms="3226">
      <class name="testscript.LoginTest">
        <test-method signature="verifyWhetherUserIsAbleLoginSuccessfullywithValidUsernameandValidPassword()[pri:0, instance:testscript.LoginTest@12591ac8]" started-at="2025-02-17T23:30:43 IST" name="verifyWhetherUserIsAbleLoginSuccessfullywithValidUsernameandValidPassword" description="Verify Whether User is able to Login Successfully with Valid Username and Valid Password" finished-at="2025-02-17T23:30:46 IST" duration-ms="3202" status="FAIL">
          <exception class="java.lang.ExceptionInInitializerError">
            <full-stacktrace>
              <![CDATA[java.lang.ExceptionInInitializerError
at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.ensureClassInitialized(MethodHandleAccessorFactory.java:300)
at java.base/jdk.internal.reflect.MethodHandleAccessorFactory.newConstructorAccessor(MethodHandleAccessorFactory.java:103)
at java.base/jdk.internal.reflect.ReflectionFactory.newConstructorAccessor(ReflectionFactory.java:200)
at java.base/java.lang.reflect.Constructor.acquireConstructorAccessor(Constructor.java:549)
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486)
at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:40)
at org.testng.internal.objects.InstanceCreator.newInstance(InstanceCreator.java:61)
at org.testng.ITestObjectFactory.newInstance(ITestObjectFactory.java:10)
at org.testng.internal.objects.SimpleObjectDispenser.dispense(SimpleObjectDispenser.java:61)
at org.testng.internal.objects.GuiceBasedObjectDispenser.dispenseObject(GuiceBasedObjectDispenser.java:41)
at org.testng.internal.objects.GuiceBasedObjectDispenser.dispense(GuiceBasedObjectDispenser.java:31)
at org.testng.internal.BaseTestMethod.computeRetryAnalyzerInstanceToUse(BaseTestMethod.java:868)
at org.testng.internal.BaseTestMethod.getRetryAnalyzerConsideringMethodParameters(BaseTestMethod.java:832)
at org.testng.internal.BaseTestMethod.getRetryAnalyzer(BaseTestMethod.java:693)
at org.testng.internal.invokers.TestInvoker.shouldRetryTestMethod(TestInvoker.java:572)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:749)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: java.lang.ClassCastException: class org.apache.logging.slf4j.SLF4JLogger cannot be cast to class freemarker.log.Logger (org.apache.logging.slf4j.SLF4JLogger and freemarker.log.Logger are in unnamed module of loader 'app')
at retry.Retry.<clinit>(Retry.java:12)
... 41 more
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.ExceptionInInitializerError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyWhetherUserIsAbleLoginSuccessfullywithValidUsernameandValidPassword -->
        <test-method is-config="true" signature="initialiseBrowser(java.lang.String)[pri:0, instance:testscript.LoginTest@12591ac8]" started-at="2025-02-17T23:30:43 IST" name="initialiseBrowser" finished-at="2025-02-17T23:30:45 IST" duration-ms="2051" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initialiseBrowser -->
      </class> <!-- testscript.LoginTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
